# name: "user_srv"
# mysql:
#   host: "go-uccs-1"
#   port: 3306
#   user: "root"
#   password: 123456
#   db: "mxshop_user_srv"
# consul:
#   host: "go-consul"
#   port: 8500

host: "go-nacos"
port: 8848
namespace: "cd509055-38c2-418f-bfae-dae07c645eeb"
user: "nacos"
password: "nacos"
dataid: "userop-srv.json"
group: "dev"